// const playerName = state.filter(function (state) {
//     return pilot.name;
//   });
  
// console.log(playerName)

// export default playerName

export default `Álex Abrines
Quincy Acy
Jaylen Adams
Steven Adams
Bam Adebayo
Deng Adel
DeVaughn Akoon-Purcell
LaMarcus Aldridge
Rawle Alkins
Grayson Allen
Jarrett Allen
Kadeem Allen
Al-Farouq Aminu
Justin Anderson
Kyle Anderson
Ryan Anderson
Ike Anigbogu
Giannis Antetokounmpo
Kostas Antetokounmpo
Carmelo Anthony
OG Anunoby
Ryan Arcidiacono
Trevor Ariza
D.J. Augustin
Deandre Ayton
Dwayne Bacon
Marvin Bagley
Ron Baker
Wade Baldwin
Lonzo Ball
Mo Bamba
J.J. Barea
Harrison Barnes
Will Barton
Keita Bates-Diop
Nicolas Batum
Jerryd Bayless
Aron Baynes
Kent Bazemore
Bradley Beal
Malik Beasley
Michael Beasley
Marco Belinelli
Jordan Bell
DeAndre' Bembry
Dragan Bender
Dairis Bertāns
Dāvis Bertāns
Patrick Beverley
Khem Birch
Bismack Biyombo
Nemanja Bjelica
Antonio Blakeney
Eric Bledsoe
Jaron Blossomgame
Bojan Bogdanović
Andrew Bogut
Jonah Bolden
Isaac Bonga
Devin Booker
Chris Boucher
Avery Bradley
Tony Bradley
Corey Brewer
Mikal Bridges
Isaiah Briscoe
Ryan Broekhoff
Malcolm Brogdon
Dillon Brooks
MarShon Brooks
Bruce Brown
Jaylen Brown
Lorenzo Brown
Sterling Brown
Troy Brown
Jalen Brunson
Thomas Bryant
Reggie Bullock
Trey Burke
Alec Burks
Deonte Burton
Jimmy Butler
Bruno Caboclo
José Calderón
Kentavious Caldwell-Pope
Isaiah Canaan
Clint Capela
DeMarre Carroll
Jevon Carter
Vince Carter
Wendell Carter
Michael Carter-Williams
Alex Caruso
Omri Casspi
Willie Cauley-Stein
Troy Caupain
Tyler Cavanaugh
Tyson Chandler
Wilson Chandler
Joe Chealey
Chris Chiozza
Marquese Chriss
Gary Clark
Ian Clark
Jordan Clarkson
John Collins
Zach Collins
Darren Collison
Bonzie Colson
Mike Conley
Pat Connaughton
Quinn Cook
DeMarcus Cousins
Robert Covington
Allen Crabbe
Torrey Craig
Jamal Crawford
Mitch Creek
Jae Crowder
Dante Cunningham
Seth Curry
Stephen Curry
Troy Daniels
Anthony Davis
Deyonta Davis
Ed Davis
Tyler Davis
Dewayne Dedmon
Sam Dekker
Ángel Delgado
Matthew Dellavedova
Luol Deng
DeMar DeRozan
Marcus Derrickson
Cheick Diallo
Hamidou Diallo
Gorgui Dieng
Spencer Dinwiddie
Donte DiVincenzo
Luka Dončić
Tyler Dorsey
Damyean Dotson
PJ Dozier
Goran Dragić
Andre Drummond
Jared Dudley
Kris Dunn
Kevin Durant
Trevon Duval
Vince Edwards
Henry Ellenson
Wayne Ellington
Joel Embiid
James Ennis
Drew Eubanks
Jawun Evans
Tyreke Evans
Dante Exum
Kenneth Faried
Derrick Favors
Cristiano Felício
Raymond Felton
Terrance Ferguson
Yogi Ferrell
Dorian Finney-Smith
Bryn Forbes
Evan Fournier
De'Aaron Fox
Melvin Frazier
Tim Frazier
Jimmer Fredette
Channing Frye
Markelle Fultz
Danilo Gallinari
Langston Galloway
Billy Garrett
Marc Gasol
Pau Gasol
Rudy Gay
Paul George
Taj Gibson
Harry Giles
Shai Gilgeous-Alexander
Rudy Gobert
Brandon Goodwin
Aaron Gordon
Eric Gordon
Marcin Gortat
Devonte' Graham
Treveon Graham
Jerami Grant
Jerian Grant
Donte Grantham
Danny Green
Draymond Green
Gerald Green
JaMychal Green
Jeff Green
Blake Griffin
Daniel Hamilton
Dusty Hannahs
Tim Hardaway
James Harden
Maurice Harkless
Montrezl Harrell
Devin Harris
Gary Harris
Joe Harris
Tobias Harris
Andrew Harrison
Shaquille Harrison
Josh Hart
Isaiah Hartenstein
Udonis Haslem
Gordon Hayward
John Henson
Juan Hernangómez
Willy Hernangómez
Mario Hezonja
Isaiah Hicks
Buddy Hield
Haywood Highsmith
Nenê Hilário
George Hill
Solomon Hill
Aaron Holiday
Jrue Holiday
Justin Holiday
John Holland
Rondae Hollis-Jefferson
Richaun Holmes
Rodney Hood
Al Horford
Danuel House
Dwight Howard
Kevin Huerter
Isaac Humphries
R.J. Hunter
Chandler Hutchison
Serge Ibaka
Andre Iguodala
Ersan İlyasova
Joe Ingles
Andre Ingram
Brandon Ingram
Kyrie Irving
Jonathan Isaac
Wesley Iwundu
Demetrius Jackson
Frank Jackson
Jaren Jackson
Josh Jackson
Justin Jackson
Reggie Jackson
LeBron James
Amile Jefferson
John Jenkins
Jonas Jerebko
Alize Johnson
Amir Johnson
B.J. Johnson
James Johnson
Stanley Johnson
Tyler Johnson
Wesley Johnson
Nikola Jokić
Damian Jones
Derrick Jones
Jalen Jones
Jemerrio Jones
Terrence Jones
Tyus Jones
DeAndre Jordan
Cory Joseph
Frank Kaminsky
Enes Kanter
Luke Kennard
Michael Kidd-Gilchrist
George King
Maxi Kleber
Brandon Knight
Kevin Knox
Furkan Korkmaz
Luke Kornet
Kyle Korver
Kosta Koufos
Rodions Kurucs
Kyle Kuzma
Skal Labissière
Jeremy Lamb
Zach LaVine
Jake Layman
T.J. Leaf
Courtney Lee
Damion Lee
Walt Lemon
Alex Len
Kawhi Leonard
Meyers Leonard
Jon Leuer
Caris LeVert
Damian Lillard
Jeremy Lin
Shaun Livingston
Zach Lofton
Kevon Looney
Brook Lopez
Robin Lopez
Kevin Love
Kyle Lowry
Jordan Loyd
Kalin Lucas
Timothé Luwawu-Cabarrot
Tyler Lydon
Trey Lyles
Scott Machado
Shelvin Mack
Daryl Macon
J.P. Macura
Ian Mahinmi
Thon Maker
Boban Marjanović
Lauri Markkanen
Jarell Martin
Frank Mason
Yante Maten
Wesley Matthews
Luc Mbah a Moute
Tahjere McCall
Patrick McCaw
CJ McCollum
T.J. McConnell
Doug McDermott
JaVale McGee
Rodney McGruder
Alfonzo McKinnie
Ben McLemore
Jordan McRae
Jodie Meeks
Salah Mejri
De'Anthony Melton
Chimezie Metu
Khris Middleton
C.J. Miles
Darius Miller
Malcolm Miller
Patty Mills
Paul Millsap
Shake Milton
Nikola Mirotić
Donovan Mitchell
Naz Mitrou-Long
Malik Monk
Greg Monroe
E'Twaun Moore
Eric Moreland
Jaylen Morris
Marcus Morris
Markieff Morris
Monte Morris
Donatas Motiejūnas
Johnathan Motley
Emmanuel Mudiay
Jamal Murray
Džanan Musa
Mike Muscala
Sviatoslav Mykhailiuk
Abdel Nader
Larry Nance
Shabazz Napier
Raul Neto
Georges Niang
Joakim Noah
Nerlens Noel
Dirk Nowitzki
Frank Ntilikina
James Nunnally
Jusuf Nurkić
David Nwaba
Royce O'Neale
Kyle O'Quinn
Semi Ojeleye
Jahlil Okafor
Élie Okobo
Josh Okogie
Victor Oladipo
Kelly Olynyk
Cedi Osman
Kelly Oubre
Zaza Pachulia
Jabari Parker
Tony Parker
Chandler Parsons
Patrick Patterson
Justin Patton
Chris Paul
Cameron Payne
Elfrid Payton
Gary Payton II
Theo Pinson
Mason Plumlee
Miles Plumlee
Jakob Pöltl
Quincy Pondexter
Otto Porter
Bobby Portis
Dwight Powell
Norman Powell
Alex Poythress
Zhou Qi
Ivan Rabb
Chasson Randle
Julius Randle
J.J. Redick
Davon Reed
Cameron Reynolds
Josh Richardson
Malachi Richardson
Austin Rivers
Devin Robinson
Duncan Robinson
Glenn Robinson III
Jerome Robinson
Mitchell Robinson
Rajon Rondo
Derrick Rose
Terrence Ross
Terry Rozier
Ricky Rubio
D'Angelo Russell
Domantas Sabonis
Brandon Sampson
JaKarr Sampson
Dario Šarić
Tomáš Satoranský
Dennis Schröder
Mike Scott
Thabo Sefolosha
Wayne Selden
Collin Sexton
Landry Shamet
Iman Shumpert
Pascal Siakam
Jordan Sibert
Ben Simmons
Jonathon Simmons
Kobi Simmons
Anfernee Simons
Marcus Smart
Dennis Smith
Ish Smith
J.R. Smith
Jason Smith
Zhaire Smith
Tony Snell
Ray Spalding
Omari Spellman
Nik Stauskas
D.J. Stephens
Lance Stephenson
Edmond Sumner
Caleb Swanigan
Jayson Tatum
Jeff Teague
Garrett Temple
Miloš Teodosić
Jared Terrell
Emanuel Terry
Daniel Theis
Isaiah Thomas
Khyri Thomas
Lance Thomas
Klay Thompson
Tristan Thompson
Sindarius Thornwell
Anthony Tolliver
Karl-Anthony Towns
Gary Trent
Allonzo Trier
P.J. Tucker
Evan Turner
Myles Turner
Ekpe Udoh
Tyler Ulis
Jonas Valančiūnas
Jarred Vanderbilt
Fred VanVleet
Noah Vonleh
Nikola Vučević
Dwyane Wade
Moritz Wagner
Dion Waiters
Kemba Walker
Lonnie Walker
John Wall
Tyrone Wallace
Taurean Waller-Prince
Brad Wanamaker
T.J. Warren
Julian Washburn
Yuta Watanabe
Thomas Welsh
Russell Westbrook
Derrick White
Okaro White
Hassan Whiteside
Andrew Wiggins
Alan Williams
C.J. Williams
Johnathan Williams
Kenrich Williams
Lou Williams
Marvin Williams
Robert Williams
Troy Williams
D.J. Wilson
Justise Winslow
Christian Wood
Delon Wright
Guerschon Yabusele
Nick Young
Thaddeus Young
Trae Young
Cody Zeller
Tyler Zeller
Ante Žižić
Ivica Zubac`.split("\n");